"""TL-7. The benign corpus that did not exist on this machine, fetched.

WHAT WAS BLOCKING
-----------------
Every false-positive number in this programme was a bound, not a measurement,
because the largest clean benign agent-reasoning corpus we held was 9,503
words. The paper's own arithmetic says bounding a session-scoped monitor's
benign firing below 10% at incident trajectory length needs about 1,209,393
words, a 127x shortfall. That was reported as a limitation of the field.

It was actually a limitation of where we looked. SWE-rebench publishes 67,074
OpenHands agent trajectories on real GitHub issues, each carrying the agent's
own reasoning, generated by Qwen3-Coder-480B. They are benign by construction:
the task is to fix a bug in a repository. They are also long, with tens of
assistant reasoning turns per trajectory, which is the property every corpus we
held was missing.

WHAT THIS BUYS, PRECISELY
-------------------------
  * a MEASURED per-family benign hit rate instead of a rule-of-three bound
  * a MEASURED FPR(L, W) for every operator, instead of a modelled one
  * a SECOND MODEL FAMILY on long trajectories, so the null-diameter law can
    be checked somewhere other than the incident it was derived from

WHAT IT DOES NOT BUY
--------------------
It is not a second HARMFUL long trajectory, so it does not settle whether the
component separation itself generalises across models. Software-engineering
agents are also one task domain, and a benign rate measured there does not
transfer automatically to, say, a security-tooling agent whose ordinary
vocabulary is closer to the detector's. Both stated in the output.

Data is cached to the scratchpad, never into the repository. Statistics only.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import statistics
import sys

HERE = pathlib.Path(__file__).resolve().parent
BACKEND = HERE.parent.parent
FAMS = ("recognition", "norm", "discount")
LIST_NAMES = {"recognition": "_REALITY_RECOGNITION_PATTERNS",
              "norm": "_NORM_STATEMENT_PATTERNS",
              "discount": "_REALITY_DISCOUNT_PATTERNS"}
SOURCE = ("nvidia/SWE-Hero-openhands-trajectories (OpenHands scaffold, "
          "Qwen3-Coder-480B), public and ungated")


def load_patterns():
    """Same AST extraction as TL-6: read the frozen vocabulary without running
    the scoring module."""
    import ast
    mod = BACKEND / "engine" / "ring12" / "rationalization.py"
    tree = ast.parse(mod.read_text(encoding="utf-8"))
    found = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign):
            targets, val = [node.target], node.value
        elif isinstance(node, ast.Assign):
            targets, val = node.targets, node.value
        else:
            continue
        if val is None:
            continue
        for tgt in targets:
            if not isinstance(tgt, ast.Name):
                continue
            for fam, name in LIST_NAMES.items():
                if tgt.id == name and isinstance(val, (ast.List, ast.Tuple)):
                    pats = []
                    for el in val.elts:
                        if (isinstance(el, ast.Call) and el.args
                                and isinstance(el.args[0], ast.Constant)):
                            pats.append(el.args[0].value)
                    found[fam] = pats
    return {f: [re.compile(p, re.I) for p in found[f]] for f in FAMS}


def harvest(cache: pathlib.Path, target_words: int, parquet: pathlib.Path):
    """Extract assistant reasoning from a LOCAL parquet shard into jsonl.

    Reading the remote 2 GB single-file dataset failed repeatedly: fsspec's
    async fetcher aborts part-way through both iter_batches and whole-row-group
    reads. The sharded NVIDIA mirror downloads cleanly at 152 MB a shard, so the
    fetch is done by huggingface_hub first and this only reads local bytes.
    """
    if cache.exists():
        got = n = 0
        for line in cache.open(encoding="utf-8"):
            got += json.loads(line)["words"]
            n += 1
        if got >= target_words:
            print(f"  cache hit: {n:,} trajectories, {got:,} words")
            return
    import pyarrow.parquet as pq
    pf = pq.ParquetFile(parquet)
    print(f"  reading {parquet.name}: {pf.metadata.num_rows:,} trajectories")
    total_words = ntraj = 0
    done = False
    with cache.open("w", encoding="utf-8") as out:
        for rb in pf.iter_batches(batch_size=64, columns=["trajectory"]):
            for row in rb.to_pylist():
                steps = [m.get("content") for m in row["trajectory"]
                         if m.get("role") == "assistant"
                         and isinstance(m.get("content"), str)
                         and m.get("content").strip()]
                if not steps:
                    continue
                w = sum(len(x.split()) for x in steps)
                out.write(json.dumps({"steps": steps, "words": w}) + "\n")
                total_words += w
                ntraj += 1
                if total_words >= target_words:
                    done = True
                    break
            if done:
                break
    print(f"  harvested {ntraj:,} trajectories, {total_words:,} words")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", type=pathlib.Path, required=True)
    ap.add_argument("--target-words", type=int, default=1_500_000)
    ap.add_argument("--parquet", type=pathlib.Path, required=True)
    ap.add_argument("--out", type=pathlib.Path)
    a = ap.parse_args()

    pats = load_patterns()
    print("=" * 78)
    print("TL-7  MEASURED BENIGN RATE ON A REAL LONG-TRAJECTORY CORPUS")
    print("=" * 78)
    a.cache.parent.mkdir(parents=True, exist_ok=True)
    harvest(a.cache, a.target_words, a.parquet)

    # ── measure ────────────────────────────────────────────────────────────
    n_traj = n_steps = n_words = 0
    hits = {f: 0 for f in FAMS}
    traj_hits = {f: 0 for f in FAMS}
    lengths = []
    co_steps = 0
    traj_all_three = 0
    diameters = []
    for line in a.cache.open(encoding="utf-8"):
        rec = json.loads(line)
        steps = rec["steps"]
        n_traj += 1
        n_steps += len(steps)
        n_words += rec["words"]
        lengths.append(len(steps))
        pos = {f: [] for f in FAMS}
        for i, s in enumerate(steps):
            lab = [f for f in FAMS if any(p.search(s) for p in pats[f])]
            for f in lab:
                hits[f] += 1
                pos[f].append(i)
            if len(lab) == 3:
                co_steps += 1
        for f in FAMS:
            if pos[f]:
                traj_hits[f] += 1
        if all(pos[f] for f in FAMS):
            traj_all_three += 1
            best = None
            for x in pos["recognition"]:
                for y in pos["norm"]:
                    for z in pos["discount"]:
                        sp = max(x, y, z) - min(x, y, z)
                        if best is None or sp < best:
                            best = sp
            diameters.append(best)

    print("\n" + "-" * 78)
    print("CORPUS")
    print("-" * 78)
    print(f"  trajectories        {n_traj:,}")
    print(f"  assistant steps     {n_steps:,}")
    print(f"  reasoning words     {n_words:,}")
    lengths.sort()
    print(f"  steps/trajectory    median {lengths[len(lengths)//2]}, "
          f"p90 {lengths[int(0.9*len(lengths))]}, max {lengths[-1]}")
    print(f"  vs the 9,503 words previously held: {n_words/9503:.0f}x")

    print("\n" + "-" * 78)
    print("MEASURED BENIGN RATES (not a bound)")
    print("-" * 78)
    for f in FAMS:
        print(f"  {f:<12} {hits[f]:>7,} steps  "
              f"({100*hits[f]/max(n_steps,1):.4f}% of steps)   "
              f"{traj_hits[f]:>6,} trajectories "
              f"({100*traj_hits[f]/max(n_traj,1):.2f}%)   "
              f"{hits[f]/max(n_words,1):.3e} per word")
    print(f"\n  ALL THREE in one step        {co_steps:,} "
          f"({100*co_steps/max(n_steps,1):.5f}%)")
    print(f"  ALL THREE anywhere in a traj {traj_all_three:,} "
          f"({100*traj_all_three/max(n_traj,1):.3f}%)")
    if diameters:
        diameters.sort()
        print(f"  benign diameter when present: median "
              f"{diameters[len(diameters)//2]}, min {diameters[0]}, "
              f"max {diameters[-1]}")

    # ── the number the paper could not previously state ────────────────────
    print("\n" + "=" * 78)
    print("WHAT THIS SETTLES")
    print("=" * 78)
    target = 1_209_393
    if n_words >= target:
        print(f"  The corpus needed to bound a latched session monitor's benign")
        print(f"  firing below 10% at incident length was {target:,} words.")
        print(f"  This corpus is {n_words:,}. The bound is now MEASURABLE.")
        print(f"  A latched monitor fires on a benign trajectory whenever all")
        print(f"  three families appear anywhere in it: measured "
              f"{100*traj_all_three/max(n_traj,1):.3f}% "
              f"({traj_all_three:,}/{n_traj:,}).")
    else:
        print(f"  {n_words:,} words is short of the {target:,} the 10% bound "
              f"needs; rates above are still the best available.")
    print()
    print("  SCOPE, STATED WITH THE RESULT: these are software-engineering")
    print("  agents on GitHub issues, one task domain and one model family")
    print("  (Qwen3-Coder-480B). A benign rate measured here does not transfer")
    print("  automatically to an agent whose ordinary vocabulary sits closer to")
    print("  the detector's, such as a security-tooling agent. This is a real")
    print("  measurement of a real population, not of every population.")

    doc = {"_what_this_is": "Measured benign hit rates for the three families "
                            "on a large external long-trajectory corpus of "
                            "benign software-engineering agent reasoning.",
           "_source": SOURCE,
           "_scope_limit": "One task domain, one model family. Not a universal "
                           "benign rate.",
           "trajectories": n_traj, "steps": n_steps, "words": n_words,
           "steps_per_trajectory": {
               "median": lengths[len(lengths)//2],
               "p90": lengths[int(0.9*len(lengths))], "max": lengths[-1]},
           "hits_steps": hits, "hits_trajectories": traj_hits,
           "rate_per_step": {f: hits[f]/max(n_steps, 1) for f in FAMS},
           "rate_per_word": {f: hits[f]/max(n_words, 1) for f in FAMS},
           "all_three_one_step": co_steps,
           "all_three_in_trajectory": traj_all_three,
           "latched_benign_firing_rate": traj_all_three/max(n_traj, 1),
           "benign_diameters": {
               "n": len(diameters),
               "median": statistics.median(diameters) if diameters else None,
               "min": min(diameters) if diameters else None,
               "max": max(diameters) if diameters else None}}
    if a.out:
        a.out.parent.mkdir(parents=True, exist_ok=True)
        a.out.write_text(json.dumps(doc, indent=1), encoding="utf-8")
        print(f"\nwrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
